name: Build MeiaDouze

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-all:
    name: Build executables for all platforms
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v2
        with:
          python-version: "3.11"

      - name: Install Flet & dependencies
        run: |
          cd app
          uv sync

      - name: Build Windows EXE
        run: |
          cd app
          uv run flet build windows --pyproject ./pyproject.toml

      - name: Build macOS DMG
        run: |
          cd app
          uv run flet build macos --pyproject ./pyproject.toml

      - name: Build Linux AppImage
        run: |
          cd app
          uv run flet build linux --pyproject ./pyproject.toml

      - name: Build Linux DEB
        run: |
          cd app
          uv run flet build linux --format deb --pyproject ./pyproject.toml

      - name: Build Linux RPM
        run: |
          cd app
          uv run flet build linux --format rpm --pyproject ./pyproject.toml

      - name: Build Android APK
        run: |
          cd app
          uv run flet build android --pyproject ./pyproject.toml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: |
            app/build/**
